name: grip-on-software/bigboat-python-api
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4.6.0
        with:
          python-version: "${{ matrix.python }}"
      - run: pip install -r requirements.txt
      - run: pip install -r test-requirements.txt
      - run: pip install coveralls
      - run: make coverage
      - name: Adjust source paths in coverage for Sonar
        run: sed -i "s/<source>\/home\/runner\/work\/bigboat-python-api\/bigboat-python-api<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/work/bigboat-python-api/bigboat-python-api/coverage.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.9
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: coveralls
        if: "${{ success() }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    strategy:
      matrix:
        python:
        - '3.8.16'
        - '3.11.2'
